basedir: /

# html lang
language: "it"

# main menu navigation
menu:
  welcome: welcome
  talks_speakers: talk e speaker
  sponsor: sponsor
  # scommentare per generare pagina
  # schedule: schedule
  # menu item for workshop
  workshop: workshop

# workshops submenu (comment out if only one workshop: add items for multiple workshops)
workshop_submenu:
  RabbitMQ: RabbitMQ
  introduzione_kubernetes: Introduzione a Kubernetes
  MLOps_Amazon_SageMaker: MLOps ed Amazon SageMaker

# welcome submenu
welcome_submenu:
  about: about
  coc: codice di condotta
  scholarships: scholarship
  where: dove e come
  # delete this row to take out of the menu
  # cfp: call for paper

# stylesheets loaded in the <head>
stylesheets:
- /assets/css/global.css

# scripts loaded in the end of the body / commented out to prevent errors in compiling layout.pug
scripts:
- /assets/js/menu.js
